name: Vuedc CI
on:
  pull_request:
    branches:
      - "*"
env:
  STORE_PATH: ""

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/env-setup
        with:
          node-version: "18.18.0"
          pnpm-version: "8.7.5"
          os: ${{ runner.os }}

      - name: Format code
        run: pnpm format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          commit_message: "style: format files"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [format]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/env-setup
        with:
          node-version: "18.18.0"
          pnpm-version: "9.9.0"
          os: ${{ runner.os }}

      - name: Lint code
        run: pnpm lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/env-setup
        with:
          node-version: "18.18.0"
          pnpm-version: "9.9.0"
          os: ${{ runner.os }}

      - name: Unittests
        run: pnpm test
