name: Vuedc CI
on:
  pull_request:
    branches:
      - "*"
env:
  STORE_PATH: ""

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/env-setup
        with:
          node-version: "18.18.0"
          pnpm-version: "9.9.0"
          os: ${{ runner.os }}

      - name: Lint code
        run: pnpm lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/env-setup
        with:
          node-version: "18.18.0"
          pnpm-version: "9.9.0"
          os: ${{ runner.os }}

      - name: Unittests
        run: pnpm test
